### PR TITLE
Both dev env machines are managed through a single Vagrantfile

### PR DESCRIPTION
**Pull request by DRvanR**
- the idp-dev vhost uses the correct socket
- suaas is now stepup

### CODE REVIEW

**Comment by DRvanR** [comment]
@arothuis

**Comment by arothuis** [comment]
Testing on my machine. In the meantime, you could change `suaas` in the docs to `stepup` as well?

**Comment by arothuis** [comment]
`vagrant up` and provisioning finished without issues.

I had to do a manual `service nginx restart && service php-fpm restart`. This was also the case on the old box. 

Manual test:
* graylog2 ✅ 
* apps (after configuration) ✅

**Comment by DRvanR** [comment]
weird that the restart was required, didn't have to do that...

**Comment by arothuis** [comment]
Could be a Mac thing?

**Pull request merged**
